//! Verified, deterministic offline vendor snapshots.
use crate::cache::{CacheStore, TreeLimits};
use arandu_query::{CacheDigest, Lockfile};
use std::fs;
use std::path::{Path, PathBuf};

pub fn materialize(
    root: &Path,
    cache: &arandu_query::CacheLayout,
    lock: &Lockfile,
) -> Result<PathBuf, String> {
    let destination = root.join("vendor").join("arandu");
    let parent = destination
        .parent()
        .ok_or("vendor destination has no parent")?;
    fs::create_dir_all(parent).map_err(|e| format!("create vendor parent: {e}"))?;
    let staging = parent.join(format!(".arandu-staging-{}", std::process::id()));
    if fs::symlink_metadata(&staging).is_ok() {
        fs::remove_dir_all(&staging).map_err(|e| format!("remove stale vendor staging: {e}"))?;
    }
    fs::create_dir_all(&staging).map_err(|e| format!("create vendor staging: {e}"))?;
    let result = (|| {
        let store = CacheStore::new(cache.clone());
        let mut metadata =
            String::from("# Generated by arandu vendor; do not edit.\nversion = 1\n\n");
        for package in &lock.packages {
            let Some(digest_text) = package.content_digest.as_deref() else {
                continue;
            };
            let digest: CacheDigest = digest_text
                .parse()
                .map_err(|e| format!("invalid digest for {}: {e}", package.source))?;
            let source = store
                .trusted_tree(digest, TreeLimits::default())
                .map_err(|e| format!("verify {}: {e}", package.source))?;
            let suffix = &digest_text[digest_text.len().saturating_sub(16)..];
            let name = format!("{}-{suffix}", sanitize(&package.name));
            let target = staging.join(&name);
            copy_tree(&source, &target)?;
            let check = store
                .verify_tree_path(&target, TreeLimits::default())
                .map_err(|e| format!("verify vendored {}: {e}", package.source))?;
            if check.digest != digest {
                return Err(format!("vendor digest changed for {}", package.source));
            }
            metadata.push_str(&format!(
                "[[package]]\nname = \"{}\"\nsource = \"{}\"\ndigest = \"{}\"\npath = \"{}\"\n\n",
                package.name, package.source, digest_text, name
            ));
        }
        fs::write(staging.join("arandu-vendor.toml"), metadata)
            .map_err(|e| format!("write vendor manifest: {e}"))?;
        if fs::symlink_metadata(&destination).is_ok() {
            let backup = parent.join(format!(".arandu-backup-{}", std::process::id()));
            if fs::symlink_metadata(&backup).is_ok() {
                fs::remove_dir_all(&backup)
                    .map_err(|e| format!("remove old vendor backup: {e}"))?;
            }
            fs::rename(&destination, &backup)
                .map_err(|e| format!("stage existing vendor tree: {e}"))?;
            if let Err(e) = fs::rename(&staging, &destination) {
                let _ = fs::rename(&backup, &destination);
                return Err(format!("publish vendor tree: {e}"));
            }
            fs::remove_dir_all(backup).map_err(|e| format!("remove vendor backup: {e}"))?;
        } else {
            fs::rename(&staging, &destination).map_err(|e| format!("publish vendor tree: {e}"))?;
        }
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_dir_all(&staging);
    }
    result.map(|()| destination)
}

fn sanitize(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}
fn copy_tree(source: &Path, target: &Path) -> Result<(), String> {
    fs::create_dir_all(target).map_err(|e| format!("create vendor directory: {e}"))?;
    for entry in fs::read_dir(source).map_err(|e| format!("read verified tree: {e}"))? {
        let entry = entry.map_err(|e| format!("read verified entry: {e}"))?;
        let kind = entry
            .file_type()
            .map_err(|e| format!("inspect verified entry: {e}"))?;
        let dst = target.join(entry.file_name());
        if kind.is_symlink() || (!kind.is_dir() && !kind.is_file()) {
            return Err(format!(
                "unsupported entry in verified tree: {}",
                entry.path().display()
            ));
        }
        if kind.is_dir() {
            copy_tree(&entry.path(), &dst)?;
        } else {
            fs::copy(entry.path(), dst).map_err(|e| format!("copy vendor file: {e}"))?;
        }
    }
    Ok(())
}
