//! Deterministic test-harness registry shared by code-generation frontends.
use std::collections::BTreeMap;

/// A compiler-validated test entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TestEntry {
    pub id: String,
    pub function: String,
}

/// Ordered registry used by harness generators and reporters.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct TestRegistry {
    entries: BTreeMap<String, TestEntry>,
}

impl TestRegistry {
    pub fn insert(&mut self, entry: TestEntry) {
        self.entries.insert(entry.id.clone(), entry);
    }

    pub fn get(&self, id: &str) -> Option<&TestEntry> {
        self.entries.get(id)
    }

    pub fn iter(&self) -> impl Iterator<Item = &TestEntry> {
        self.entries.values()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Emits the deterministic C shim used by the portable backend.
    #[must_use]
    pub fn emit_c_entrypoint(&self) -> String {
        let mut output =
            String::from("/* generated by arandu test harness */\n#include <stddef.h>\n\n");
        for entry in self.iter() {
            output.push_str("extern void ");
            output.push_str(&sanitize_identifier(&entry.function));
            output.push_str("(void);\n");
        }
        output.push_str("\nint main(void) {\n");
        for entry in self.iter() {
            output.push_str("    ");
            output.push_str(&sanitize_identifier(&entry.function));
            output.push_str("();\n");
        }
        output.push_str("    return 0;\n}\n");
        output
    }
}

fn sanitize_identifier(id: &str) -> String {
    let mut result = String::with_capacity(id.len());
    for byte in id.bytes() {
        if byte.is_ascii_alphanumeric() || byte == b'_' {
            result.push(byte as char);
        } else {
            result.push('_');
        }
    }
    if result.is_empty() || result.as_bytes()[0].is_ascii_digit() {
        result.insert(0, '_');
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_is_deterministic_and_replaces_duplicate_ids() {
        let mut registry = TestRegistry::default();
        registry.insert(TestEntry {
            id: "z".into(),
            function: "zeta".into(),
        });
        registry.insert(TestEntry {
            id: "a".into(),
            function: "alpha".into(),
        });
        registry.insert(TestEntry {
            id: "a".into(),
            function: "updated".into(),
        });
        assert_eq!(registry.len(), 2);
        assert_eq!(
            registry
                .iter()
                .map(|entry| entry.id.as_str())
                .collect::<Vec<_>>(),
            ["a", "z"]
        );
        assert_eq!(
            registry.get("a").map(|entry| entry.function.as_str()),
            Some("updated")
        );
        assert!(registry.emit_c_entrypoint().contains("updated"));
    }
}
